### ISSUE TITLE
无法工作在主库下

### ISSUE THREAD

**Issue by fuqiang03** [sirpdboy/luci-app-autopoweroff#1]
使用master库最新的luci 无法在也页面启动和关闭 ,,只能使用restart命令

**Comment by sirpdboy** [comment]
19.07的版本吗？ 1806上测试无此现象哦。

**Comment by fuqiang03** [comment]
比19.07 版本的还高的master 官方的源码下 无法运行

**Comment by lllrrr2** [comment]
19.07官方源码，用官方luci 18.6编译成功，但功能无效，将大雕的autoreboot编译进去，可以定时重启，对比了一下，可能是init中的脚本哪有问题吧，其他文件好像没什么太大区别。请大佬帮看一下，想要定时关机功能

**Comment by lllrrr2** [comment]
测试发现，点保存在计划任务中不会添加记录
